# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='project',
        ),
        migrations.RemoveField(
            model_name='step',
            name='run',
        ),
        migrations.RemoveField(
            model_name='value',
            name='run',
        ),
        migrations.AddField(
            model_name='flow',
            name='active_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='complete_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='expired_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='interrupted_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='exited_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='flow',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
