# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
