# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='email',
            name='project',
        ),
        migrations.AddField(
            model_name='email',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='reports.Project'),
        ),
    ]
