# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170704_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='groups',
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
