# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170729_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='workspace',
            new_name='name',
        ),
    ]
