# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170816_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='urns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='expires',
            field=models.IntegerField(null=True),
        ),
    ]
