# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170704_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_event_id', models.IntegerField()),
                ('uuid', models.CharField(max_length=36)),
                ('campaign', models.CharField(max_length=200)),
                ('relative_to', models.CharField(max_length=100)),
                ('offset', models.IntegerField()),
                ('unit', models.CharField(max_length=7)),
                ('delivery_hour', models.IntegerField()),
                ('message', models.TextField()),
                ('flow', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
