# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_campaign_campaignevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
    ]
