# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170816_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flows',
            field=models.ManyToManyField(related_name='flows', to='reports.Flow'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
