# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170916_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flows',
            field=models.ManyToManyField(blank=True, null=True, related_name='flows', to='reports.Flow'),
        ),
    ]
