# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170916_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='values',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='flows',
            field=models.ManyToManyField(related_name='flows', to='reports.Flow'),
        ),
    ]
