# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170922_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='run',
            name='values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='node',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
