# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170719_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='flow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
