# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170924_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.IntegerField()),
                ('name', models.CharField(max_length=225, null=True)),
                ('language_preference', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.DateField()),
                ('district', models.IntegerField()),
                ('area', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('sector', models.IntegerField()),
                ('telephone_number', models.IntegerField()),
                ('alt_number', models.CharField(max_length=225)),
                ('date_of_consent', models.DateField()),
                ('art_type', models.CharField(max_length=50)),
                ('more_info', models.CharField(max_length=225)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
            ],
        ),
    ]
