# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_artcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontact',
            name='created_by',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='district',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='language_preference',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='sector',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='status',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='telephone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='voice_id',
            field=models.BigIntegerField(),
        ),
    ]
