# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_email_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignevent',
            options={'ordering': ['-created_on']},
        ),
    ]
