# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20180406_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontact',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='alt_number',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='art_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='date_of_consent',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='language_preference',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='more_info',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='sector',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artcontact',
            name='status',
            field=models.BigIntegerField(null=True),
        ),
    ]
