# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_cdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='amaflags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='billsec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='calldate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='endcall',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='enterq',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='import_cdr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='leaveq',
            field=models.DateTimeField(null=True),
        ),
    ]
