# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20180412_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Workspace'),
        ),
    ]
